# Competitor Analysis Pipeline
# Orchestrates 5 agents in sequence to analyze a competitor

name: competitor-analysis-pipeline
description: Full competitor intelligence analysis from Instagram handle
version: "1.0"

trigger:
  type: manual
  input:
    competitor_id: uuid
    run_id: uuid

agents:
  - name: discovery
    agent: "@discovery"
    description: "Discover channels from Instagram profile"
    status_label: "discovering"
    progress: 0-20
    timeout: 60s
    retry: 2
    on_error: fail_pipeline

  - name: scraper
    agent: "@scraper"
    description: "Extract raw data from each channel"
    status_label: "scraping"
    progress: 20-50
    timeout: 120s
    retry: 2
    depends_on: discovery
    on_error: fail_pipeline

  - name: analyst
    agent: "@analyst"
    description: "Categorize and calculate metrics"
    status_label: "analyzing"
    progress: 50-70
    timeout: 30s
    retry: 1
    depends_on: scraper
    on_error: fail_pipeline

  - name: enrichment
    agent: "@enrichment"
    description: "Generate LLM insights"
    status_label: "enriching"
    progress: 70-90
    timeout: 60s
    retry: 2
    depends_on: analyst
    on_error: continue_without

  - name: report
    agent: "@report"
    description: "Persist results to database"
    status_label: "completed"
    progress: 90-100
    timeout: 30s
    retry: 3
    depends_on: [analyst, enrichment]
    on_error: fail_pipeline

on_failure:
  - update_run_status: "failed"
  - store_error_message: true
